# Generated by Django 3.1 on 2020-08-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200823_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='describtion',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
